package ${entity.javaPackage};

import lombok.Data;

/**
 * This code is generated by FreeMarker
 * @author lvzb.software@qq.com
 *
 */
@Data
public class ${entity.className}
{
    /********** attribute ***********/
<#list entity.properties as property>
    private ${property.javaType} ${property.propertyName};

</#list>

}